// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent execution status.
type NodeExecutionStatus int32

const (
	NodeExecutionStatus_PENDING   NodeExecutionStatus = 0
	NodeExecutionStatus_SUCCEEDED NodeExecutionStatus = 1
	NodeExecutionStatus_FAILED    NodeExecutionStatus = 2
	NodeExecutionStatus_EXCEPTION NodeExecutionStatus = 3
	NodeExecutionStatus_STOPPED   NodeExecutionStatus = 4
	NodeExecutionStatus_PAUSED    NodeExecutionStatus = 5
)

// Enum value maps for NodeExecutionStatus.
var (
	NodeExecutionStatus_name = map[int32]string{
		0: "PENDING",
		1: "SUCCEEDED",
		2: "FAILED",
		3: "EXCEPTION",
		4: "STOPPED",
		5: "PAUSED",
	}
	NodeExecutionStatus_value = map[string]int32{
		"PENDING":   0,
		"SUCCEEDED": 1,
		"FAILED":    2,
		"EXCEPTION": 3,
		"STOPPED":   4,
		"PAUSED":    5,
	}
)

func (x NodeExecutionStatus) Enum() *NodeExecutionStatus {
	p := new(NodeExecutionStatus)
	*p = x
	return p
}

func (x NodeExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (NodeExecutionStatus) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x NodeExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeExecutionStatus.Descriptor instead.
func (NodeExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// Empty message.
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// Request to run an agent.
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`       // Process id.
	Nid           string                 `protobuf:"bytes,2,opt,name=nid,proto3" json:"nid,omitempty"`       // Node id.
	Inputs        *structpb.Value        `protobuf:"bytes,3,opt,name=inputs,proto3" json:"inputs,omitempty"` // Inputs.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RunRequest) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *RunRequest) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *RunRequest) GetInputs() *structpb.Value {
	if x != nil {
		return x.Inputs
	}
	return nil
}

// Update from agent.
type AgentUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RelayMessage:
	//
	//	*AgentUpdate_Log
	//	*AgentUpdate_Output
	RelayMessage  isAgentUpdate_RelayMessage `protobuf_oneof:"relay_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUpdate) Reset() {
	*x = AgentUpdate{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUpdate) ProtoMessage() {}

func (x *AgentUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUpdate.ProtoReflect.Descriptor instead.
func (*AgentUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentUpdate) GetRelayMessage() isAgentUpdate_RelayMessage {
	if x != nil {
		return x.RelayMessage
	}
	return nil
}

func (x *AgentUpdate) GetLog() string {
	if x != nil {
		if x, ok := x.RelayMessage.(*AgentUpdate_Log); ok {
			return x.Log
		}
	}
	return ""
}

func (x *AgentUpdate) GetOutput() *AgentOutput {
	if x != nil {
		if x, ok := x.RelayMessage.(*AgentUpdate_Output); ok {
			return x.Output
		}
	}
	return nil
}

type isAgentUpdate_RelayMessage interface {
	isAgentUpdate_RelayMessage()
}

type AgentUpdate_Log struct {
	Log string `protobuf:"bytes,1,opt,name=log,proto3,oneof"`
}

type AgentUpdate_Output struct {
	Output *AgentOutput `protobuf:"bytes,2,opt,name=output,proto3,oneof"`
}

func (*AgentUpdate_Log) isAgentUpdate_RelayMessage() {}

func (*AgentUpdate_Output) isAgentUpdate_RelayMessage() {}

// Log message.
type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Log) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Agent output.
type AgentOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent execution status
	Status NodeExecutionStatus `protobuf:"varint,1,opt,name=status,proto3,enum=agent.NodeExecutionStatus" json:"status,omitempty"`
	// agent outputs
	Outputs *structpb.Value `protobuf:"bytes,2,opt,name=outputs,proto3" json:"outputs,omitempty"`
	// agent error message
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// agent exception message
	Exception     string `protobuf:"bytes,4,opt,name=exception,proto3" json:"exception,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentOutput) Reset() {
	*x = AgentOutput{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentOutput) ProtoMessage() {}

func (x *AgentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentOutput.ProtoReflect.Descriptor instead.
func (*AgentOutput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentOutput) GetStatus() NodeExecutionStatus {
	if x != nil {
		return x.Status
	}
	return NodeExecutionStatus_PENDING
}

func (x *AgentOutput) GetOutputs() *structpb.Value {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *AgentOutput) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentOutput) GetException() string {
	if x != nil {
		return x.Exception
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\x1a\x1cgoogle/protobuf/struct.proto\"\a\n" +
	"\x05Empty\"`\n" +
	"\n" +
	"RunRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\x12\x10\n" +
	"\x03nid\x18\x02 \x01(\tR\x03nid\x12.\n" +
	"\x06inputs\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x06inputs\"`\n" +
	"\vAgentUpdate\x12\x12\n" +
	"\x03log\x18\x01 \x01(\tH\x00R\x03log\x12,\n" +
	"\x06output\x18\x02 \x01(\v2\x12.agent.AgentOutputH\x00R\x06outputB\x0f\n" +
	"\rrelay_message\"\x1f\n" +
	"\x03Log\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\xa7\x01\n" +
	"\vAgentOutput\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.agent.NodeExecutionStatusR\x06status\x120\n" +
	"\aoutputs\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\aoutputs\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1c\n" +
	"\texception\x18\x04 \x01(\tR\texception*e\n" +
	"\x13NodeExecutionStatus\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tSUCCEEDED\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\r\n" +
	"\tEXCEPTION\x10\x03\x12\v\n" +
	"\aSTOPPED\x10\x04\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x052f\n" +
	"\fAgentService\x12.\n" +
	"\x03Run\x12\x11.agent.RunRequest\x1a\x12.agent.AgentUpdate0\x01\x12&\n" +
	"\bShutdown\x12\f.agent.Empty\x1a\f.agent.EmptyB1Z/github.com/yunis-du/actflow-agent-sdk/go-sdk/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_proto_goTypes = []any{
	(NodeExecutionStatus)(0), // 0: agent.NodeExecutionStatus
	(*Empty)(nil),            // 1: agent.Empty
	(*RunRequest)(nil),       // 2: agent.RunRequest
	(*AgentUpdate)(nil),      // 3: agent.AgentUpdate
	(*Log)(nil),              // 4: agent.Log
	(*AgentOutput)(nil),      // 5: agent.AgentOutput
	(*structpb.Value)(nil),   // 6: google.protobuf.Value
}
var file_agent_proto_depIdxs = []int32{
	6, // 0: agent.RunRequest.inputs:type_name -> google.protobuf.Value
	5, // 1: agent.AgentUpdate.output:type_name -> agent.AgentOutput
	0, // 2: agent.AgentOutput.status:type_name -> agent.NodeExecutionStatus
	6, // 3: agent.AgentOutput.outputs:type_name -> google.protobuf.Value
	2, // 4: agent.AgentService.Run:input_type -> agent.RunRequest
	1, // 5: agent.AgentService.Shutdown:input_type -> agent.Empty
	3, // 6: agent.AgentService.Run:output_type -> agent.AgentUpdate
	1, // 7: agent.AgentService.Shutdown:output_type -> agent.Empty
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[2].OneofWrappers = []any{
		(*AgentUpdate_Log)(nil),
		(*AgentUpdate_Output)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
